# Generated by Django 3.1.4 on 2020-12-10 19:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_add_official_and_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipost',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikipost',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikipost',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.wikipost'),
        ),
        migrations.AddField(
            model_name='wikipost',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wikipost',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='wikipost',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='wikipost',
            unique_together={('parent', 'slug')},
        ),
    ]
