# Generated by Django 3.1.5 on 2021-01-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20210120_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='Page_id',
            new_name='page_id',
        ),
    ]
